### ISSUE TITLE
Office 16 or Office 21?

### ISSUE THREAD

**Issue by Saeedjaanz** [21Z/Microsoft-Office-2021#10]
So, your first method doesn't work honestly. 

......Processing.......................
No Office KMS licenses were found on the system.
......Exiting...............................

.....Processing........................
LICENSE NAME: Office 16, Office160365ProPlusR_Subcription1 edition

WHY IT SAYS OFFICE 16?? In you provided images, it says Office 21???

**Comment by 21Z** [comment]
sorry for the late reply,
that seems to be a license already installed in ur system before
could u send the full logs (or screenshot) so i can understand further?

**Comment by Saeedjaanz** [comment]
![By copy pasting commands to cmd](https://github.com/21Z/Microsoft-Office-2021/assets/134127527/7d311c00-cc75-4310-b5ab-112c0ea954a1)
![By copy pasting commands to cmd 2](https://github.com/21Z/Microsoft-Office-2021/assets/134127527/0bea266b-d59f-42ab-9b6c-35857cd08052)
This is from Method no 1.

**Comment by Saeedjaanz** [comment]
So, I was granted the laptop in a scheme from my state institution. They provided us with the liscenced windows, Microsoft 365 and Office 2021 along with it. I have used it since four years. Now, they restricted or took back my liscence of microsoft 365 & office 2021. I loved office 2021 more than any previous versions and couldnt bear my lisence gone. So, i found your way. Plz note that by the time i was trying your activation method, there was no liscence in my office/system.

**Comment by 21Z** [comment]
you have licenses in ur pc that are no longer valid, u can ignore those...
the first screenshot shows that the activation is successful
and the second screenshot shows you didn't open cmd prompt with admin 
![image](https://github.com/21Z/Microsoft-Office-2021/assets/69188068/0eec8f4f-5455-47d3-8cc1-81fa0a7e57d2)

**Comment by Saeedjaanz** [comment]
Ok thanks. But earlier when I was trying to activate the office, I tried both methods. Now, its running on my PC. But, It keeps repeating the (Not Responding) after a while. And then, it works normal
