### ISSUE TITLE
issue while installing

### ISSUE THREAD

**Issue by LeeVolpe** [21Z/Microsoft-Office-2021#11]
So i've run into this issue where it simply states: 

"We can't install. This product can't be installed on the selected update channel. Please contact your system admin and try again" 

I tried removing office 365 that was already installed but it doesn't seem to have fixed anything.

**Comment by 21Z** [comment]
which version are u trying to install
32bit or 64bit?

**Comment by Subtilizer28** [comment]
same issue. i tried 64bit

**Comment by SilvioCorso** [comment]
i have the same problem.
i have unistalled every version of office.
![image](https://github.com/21Z/Microsoft-Office-2021/assets/34095410/2690aa92-310a-4c6a-89a5-7e309882d599)
