### ISSUE TITLE
Getting an Error at the end of activation

### ISSUE THREAD

**Issue by MauroBrandolt** [21Z/Microsoft-Office-2021#12]
i am constantly getting this error from the activation, even tried to uninstall and reinstall with your office bin to try to fix it but no success .
![image](https://github.com/21Z/Microsoft-Office-2021/assets/115196492/165296ba-2d36-49a1-a4d1-be8f68dd147f)

used both methods.

**Comment by MauroBrandolt** [comment]
Tried to restart the pc, opened one word doc, closed it and run the activatior.bat but still getting this 0x80080005 errror
![image](https://github.com/21Z/Microsoft-Office-2021/assets/115196492/56244148-d8fc-4a93-9a66-76111d300c7b)

**Comment by Nightowl36373838** [comment]
I think you should try deactivating your firewalls. antivirus(incase you're not using an antivirus......Disable Windows defender/ Virus and Threat Protection)........Check it out, just a suggestion.

**Comment by ramnistala** [comment]
I  am also getting above error. deactivated firewall, Antivirus.. but no use

**Comment by VIRIATO80** [comment]
@MauroBrandolt @ramnistala Yo need run this archive with administrator rol actived.

**Comment by Nightowl36373838** [comment]
That's cool
It works though I'm not the author of the Script

**Comment by SatyaKairi** [comment]
Disabling Firewall worked for me

**Comment by 21Z** [comment]
is this still occurring?

**Comment by MauroBrandolt** [comment]
> is this still occurring?

tbh idk, i gave up and reinstalled the 2016 version but if someone was having the same issue as me, and solved it, plz feel free to give a heads up

**Comment by 21Z** [comment]
hmm
