### ISSUE TITLE
Error while Installation

### ISSUE THREAD

**Issue by itzzzyashu** [21Z/Microsoft-Office-2021#18]
I've been trying to install **Microsoft Office 2021** from this source code since yesterday,
I also tried alternative download links as [Office 2021 Direct Download Links](https://t.co/9WHQ4K5VBA),

But While Installation I got these two errors: 
![photo_2023-09-05_20-10-29](https://github.com/21Z/Microsoft-Office-2021/assets/83384892/20ebb9b9-776f-4236-98b5-4e0663779a27)
![photo_2023-09-05_20-10-19](https://github.com/21Z/Microsoft-Office-2021/assets/83384892/b9504cf1-c356-4857-a482-64565d640aab)

I tried to download after:
- Checking my Internet Connection.
- Turned off Windows Security Firewall and Real Time Protection settings.

I noticed while installing there was a folder named _"Office16"_ and it was vanishing again and again and it didn't stay in explorer for even seconds, I searched for _ospp.vbs_ in the root of installation directory, and also in my all Hard Disk Drives but couldn't find it.
I knew that files in _Microsoft Office/Office16_ folder are important for activation of the product,
However I still got no solution, please see if it can be fixed.

Thank you.

**Comment by abdullah-zero9** [comment]
I'm facing same problem too. please fix it

**Comment by itzzzyashu** [comment]
> I'm facing same problem too. please fix it

I still don't know how to fix it.

**Comment by itzzzyashu** [comment]
> it could be the anti-virus/firewall, try turning off your anti-virus and installing again?
> i don't know about this, i just found this on the internet.
> also is your windows up-to-date, some updates could also be causing these issues...

I tried that but got the same error again.
