### ISSUE TITLE
activation issue

### ISSUE THREAD

**Issue by Haris522** [21Z/Microsoft-Office-2021#2]
I've tried many times to activate this product. i have tried CMD and batch file method, with and without microsoft account and even restart my system, but this product is still unlicensed.

**Comment by 21Z** [comment]
hi can u send what the command prompt is showing?

**Comment by creepergamingboy** [comment]
I'm having the same issue, everything above this in the CMD completes without error's 
![image](https://user-images.githubusercontent.com/42660244/229623558-708897e4-a28d-468e-b453-8382d73fd6f4.png)

**Comment by 21Z** [comment]
> I'm having the same issue, everything above this in the CMD completes without error's ![image](https://user-images.githubusercontent.com/42660244/229623558-708897e4-a28d-468e-b453-8382d73fd6f4.png)

it is activated, the one which its showing is not activated is ur trial license (ending PG343) And below u can see License (ending GF7TH) showing product activation successful, open any office application and check, it should be activated

**Comment by creepergamingboy** [comment]
![image](https://user-images.githubusercontent.com/42660244/229811543-ee933edb-3d7e-4361-9bbd-2703c8d900e8.png)

**Comment by creepergamingboy** [comment]
yes

**Comment by 21Z** [comment]
hmm, that's odd. from the pic u sent it says activation successful, also if u already opened any office app before activation, u have to reopen it after activation and check...

**Comment by Haris522** [comment]
> ![image](https://user-images.githubusercontent.com/42660244/229811543-ee933edb-3d7e-4361-9bbd-2703c8d900e8.png)
> 

Facing same issue 
I've tried with too many attempts from Downloading the zip file to till activation.(with restart), but still unlicensed...

**Comment by qriozum** [comment]
You need to uninstall the "PG343" license.

**Comment by 21Z** [comment]
> "PG343" license.

it works without uninstalling the PG343 license, because when another license is installed, the trial license wont be installed.
![image](https://user-images.githubusercontent.com/69188068/235849414-58401a6d-79ae-487c-a6fd-bf66bb8585a0.png)
see the ERROR
