### ISSUE TITLE
installing problem

### ISSUE THREAD

**Issue by lunarred420** [21Z/Microsoft-Office-2021#24]
### Describe the problem

stuck at 3% while installing for like 10 mins

### Screenshots

![image](https://github.com/21Z/Microsoft-Office-2021/assets/148389923/66684d8d-e0b6-4645-9c8d-ba81bccc33b1)

### Windows version

Windows 10 (21H2)

**Comment by 21Z** [comment]
is it still stuck? is your network slow?

**Comment by lunarred420** [comment]
> is it still stuck? is your network slow?

no, my network is not very slow its like 30mbps and ill try it now

**Comment by 21Z** [comment]
cant reproduce, could be pc-related bug

**Comment by Nepann** [comment]
????????????--I didn't create tickets, lol
