### ISSUE TITLE
Product key is not matching the installed version of Office

### ISSUE THREAD

**Issue by armish-hashmi** [21Z/Microsoft-Office-2021#5]
I am getting this error upon entering the key manually [
![activation key error](https://user-images.githubusercontent.com/107803997/230717581-cda3f595-33e7-448a-92b5-bf831ac45e87.PNG)
](url)
I used Install-x64.bat in the provided zip file for installation. Following is the installed of version 
![installation](https://user-images.githubusercontent.com/107803997/230717664-25bb7bc5-9f6b-451b-9e42-cc2ec02a1eef.PNG)

**Comment by 21Z** [comment]
please show the logs in command prompt when running the activator
